get http://localhost:3333

###

post http://localhost:3333/signup
Content-Type: application/json

{
    "username": "testUser",
    "email": "test@gmail.com",
    "password": "test123"
    
}

###

post http://localhost:3333/login
Content-Type: application/json

{
    "email": "t1@m.com",
    "password": "1234567891"
}

###

post http://localhost:3333/createTodo
Content-Type: application/json

{
    "title": "criado 1",
    "description": "the first"
}

###

get http://localhost:3333/users

###

delete http://localhost:3333/users

###

get http://localhost:3333/getTodos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG0uY29tIiwidXNlcklkIjoxOSwiaWF0IjoxNzM3MjY5NDcwfQ.UmiImRp7D9xpK3a8a2nT7wSnQUWaWT--aKc2MV4GOks
