get http://localhost:3333

###

post http://localhost:3333/signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "1234567981"
    
}

###

post http://localhost:3333/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234567981"
}


###

get http://localhost:3333/users

###

delete http://localhost:3333/users

###

get http://localhost:3333/getAllTodos

###

delete http://localhost:3333/deleteTodos